{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "def test_02():\n>       assert 1==2\nE       assert 1 == 2\n\n..\\test_case\\test_case02.py:9: AssertionError"}, "start": 1601717081680, "stop": 1601717081680, "uuid": "e353f217-45d3-4ae5-9ee1-dbe2fb156420", "historyId": "a86d7f4d8ccb629e6747bbd7bfd2e0ee", "testCaseId": "9c67115b882fe8bf85a00981acf44393", "fullName": "test_case.test_case02#test_02", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case02"}, {"name": "host", "value": "DESKTOP-GQ8RH5G"}, {"name": "thread", "value": "19232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case02"}]}